package com.github.linyuzai.arkevent;

public interface Order {

    int PUBLISH_STRATEGY_ADAPTER_TRANSACTION = -20;
    int PUBLISH_STRATEGY_ADAPTER_REMOTE = -10;
    int PUBLISH_STRATEGY_ADAPTER_SIMPLE = 0;

    int EXCEPTION_HANDLER_ADAPTER_TRANSACTION = -30;
    int EXCEPTION_HANDLER_ADAPTER_REMOTE = -20;
    int EXCEPTION_HANDLER_ADAPTER_RETHROW = -10;
    int EXCEPTION_HANDLER_ADAPTER_LOGGER = 0;

    int PUBLISH_SORTER_TRANSACTION = -20;
    int PUBLISH_SORTER_REMOTE = -10;

    default int order() {
        return 0;
    }
}
